<a href="https://colab.research.google.com/github/sushmaasav/Data-Analysis/blob/Data-Analysis/Inclass_Introduction_to_Linear_Algebra_Questions_(1)_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy.linalg as la



### Creation of Vectors and Matrices

1. Create a row vector of natural numbers of size 4.

In [ ]:
row_vector = np.array([1,2,3,4])
row_vector

array([1, 2, 3, 4])

Check the shape and type of vector.

> Indented block



In [ ]:
row_vector.shape

(4,)

In [ ]:
row_vector.dtype

dtype('int32')

2. Create a 2 x 2 matrix of all zeros, all ones, all with a value of 4 and all with random values.

In [ ]:
zero_matrix = np.zeros((2,2))
zero_matrix

array([[0., 0.],
       [0., 0.]])

In [ ]:
ones_matrix = np.ones((2,2))
ones_matrix

array([[1., 1.],
       [1., 1.]])

In [ ]:
full_matrix = np.full((2,2),4)
full_matrix

array([[4, 4],
       [4, 4]])

In [ ]:
rand_matrix = np.random.randint(1,10,(2,2))
rand_matrix

array([[7, 2],
       [4, 6]])

# Vector and Matrix Operations 


4. Find the magnitude/ L1 and L2 norm of the vector [4,6] and state which has 

*   List item
*   List item

has a highest value.


In [ ]:
vector = np.array([4,6])
vector

array([4, 6])

In [ ]:
L1 = np.linalg.norm(vector,ord=1)    #L1 norm
L2 = np.linalg.norm(vector)        #L2 norm

print('L1 Norm =',L1) 
print('L2 Norm =',L2)

L1 Norm = 10.0
L2 Norm = 7.211102550927978


In [ ]:
def high_norm(L1,L2):
    if L1>L2:
        print("L1 norm has highest value") 
    else:
        print("L2 norm has highest value")

In [ ]:
high_norm(L1,L2)

L1 norm has highest value


## Vector and Matrix Arithmetic 

5. Perform addition, subtraction, multiplication and division of two matrices of size (3 x 3)

In [ ]:
matrix_1 = np.random.randint(1,10,(3,3))
matrix_2 = np.random.randint(11,20,(3,3))
print(matrix_1)
print(matrix_2)

[[6 1 3]
 [6 6 7]
 [1 2 8]]
[[16 19 12]
 [12 15 16]
 [11 17 12]]


In [ ]:
print('Addition of 2 matrices:\n',np.add(matrix_1,matrix_2))
print('Subtraction of 2 matrices:\n',np.subtract(matrix_1,matrix_2))
print('Element wise Multiplication of 2 matrices:\n',np.multiply(matrix_1,matrix_2))
print('Division of 2 matrices:\n',np.divide(matrix_1,matrix_2))

Addition of 2 matrices:
 [[22 20 15]
 [18 21 23]
 [12 19 20]]
Subtraction of 2 matrices:
 [[-10 -18  -9]
 [ -6  -9  -9]
 [-10 -15  -4]]
Element wise Multiplication of 2 matrices:
 [[ 96  19  36]
 [ 72  90 112]
 [ 11  34  96]]
Division of 2 matrices:
 [[0.375      0.05263158 0.25      ]
 [0.5        0.4        0.4375    ]
 [0.09090909 0.11764706 0.66666667]]


## Dot product

6. Find the dot product of the matrices created above.

In [ ]:
print('Dot product of 2 matrices:\n',np.dot(matrix_1,matrix_2))

Dot product of 2 matrices:
 [[141 180 124]
 [245 323 252]
 [128 185 140]]


### Scalar and Vector Projections
7. Find the scalar and vector projections of the vector  u = 8i + 6j on vector v = i - 7j


In [ ]:
u = np.array([8,6])   # vector u 
v = np.array([1,-7])   # vector v

v_norm = np.sqrt(sum(v**2))

scalar_projection = np.dot(u,v)/v_norm
print("Scalar Projection of vector u on v is",scalar_projection)

vector_projection = (np.dot(u,v)/v_norm**2)*v
print("Vector Projection of vector u on v is",vector_projection)

Scalar Projection of vector u on v is -4.808326112068523
Vector Projection of vector u on v is [-0.68  4.76]


### Transpose of a matrix

9. Find the transpose of the matrix A 

      
      [[ 2,  3,  3,  8],
       [ 6,  7,  7,  8],
       [1, 2, 3, 4]]

In [ ]:
A = np.array([[ 2,  3,  3,  8],
   [ 6,  7,  7,  8],
   [1, 2, 3, 4]])
AT = np.transpose(A)
print(A)
print(AT)

[[2 3 3 8]
 [6 7 7 8]
 [1 2 3 4]]
[[2 6 1]
 [3 7 2]
 [3 7 3]
 [8 8 4]]


### Identity Matrix

In [ ]:
# identity matrix 
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Linear Independence
Check for linear combination of vectors. If it zero, then the set of vectors is linearly independent.

The no. of linearly independent columns will determine the no. of solutions.

Direction of two linearly dependent vectors is the same.

Determine whether the vectors are linearly independent of each other to see if the vectors form a basis,

or to determine how many independent equations there are, 

or to determine how many independent reactions there are.

The set S = {v1, v2, v3} of vectors in R3 is linearly independent if the only solution of

c1v1 + c2v2 + c3v3 = 0 
is c1, c2, c3 = 0



## Types of Matrices

In [ ]:
from numpy import array
# list of data
data = [[1, 2],[3, 4],[5, 6]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [ ]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[11, 12, 13],
[14, 15, 16],
[17, 18, 19]])


MU = np.triu(M)
print(MU)

ML = np.tril(M)
print(ML)

[[11 12 13]
 [ 0 15 16]
 [ 0  0 19]]
[[11  0  0]
 [14 15  0]
 [17 18 19]]


In [ ]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[11, 12, 13],
[14, 15, 16],
[17, 18, 19]])
print(M)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


Create Identity MAtrix

In [ ]:
eye = np.eye(5)

In [ ]:
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])